// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKt4B5zUg3fO7Lxgd51Q4Rm_YQh_I74Y',
    appId: '1:265849220146:web:36a560cf1881bdc3d7a02b',
    messagingSenderId: '265849220146',
    projectId: 'fridge-flow-dreamflow',
    authDomain: 'fridge-flow-dreamflow.firebaseapp.com',
    storageBucket: 'fridge-flow-dreamflow.firebasestorage.app',
    measurementId: 'G-F02L71FCP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHeH3fv2S4DQxaGU0lDFCeoZY5NhG2KVY',
    appId: '1:265849220146:android:c908e27d3031b2fdd7a02b',
    messagingSenderId: '265849220146',
    projectId: 'fridge-flow-dreamflow',
    storageBucket: 'fridge-flow-dreamflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoS0SYXOtXrQnqnLk5xe9V8hr_0VZDylM',
    appId: '1:265849220146:ios:4aac5cff1ecf0680d7a02b',
    messagingSenderId: '265849220146',
    projectId: 'fridge-flow-dreamflow',
    storageBucket: 'fridge-flow-dreamflow.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
